# PlatformIO pre-build step: gzips every file in web/ into include/web_assets.h, so the
# firmware can serve them compressed (browsers unpack them). Routes: index.html is "/",
# other .html files drop the extension ("/tennis"), anything else keeps its name.
import gzip
import os

Import("env")  # noqa: F821 (provided by PlatformIO)

TYPES = {".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".json": "application/json"}

project = env.subst("$PROJECT_DIR")  # noqa: F821
web_dir = os.path.join(project, "web")
out_path = os.path.join(project, "include", "web_assets.h")

lines = [
    "// Generated by tools/embed_web.py from web/ on every build. Do not edit.",
    "#pragma once",
    "#include <Arduino.h>",
    "",
    "struct WebAsset {",
    "  const char* path;",
    "  const char* type;",
    "  const uint8_t* data;  // gzip",
    "  size_t len;",
    "};",
    "",
]
table = []
raw_total = gz_total = 0
for i, name in enumerate(sorted(os.listdir(web_dir))):
    stem, ext = os.path.splitext(name)
    if ext not in TYPES:
        continue
    raw = open(os.path.join(web_dir, name), "rb").read()
    gz = gzip.compress(raw, compresslevel=9, mtime=0)  # mtime=0: same input, same bytes
    raw_total += len(raw)
    gz_total += len(gz)
    route = "/" if name == "index.html" else "/" + (stem if ext == ".html" else name)
    lines.append(f"static const uint8_t WEB_{i}[] PROGMEM = {{")
    for j in range(0, len(gz), 24):
        lines.append("  " + ", ".join(str(b) for b in gz[j:j + 24]) + ",")
    lines.append("};")
    table.append(f'  {{"{route}", "{TYPES[ext]}", WEB_{i}, sizeof(WEB_{i})}},')

lines += ["", "static const WebAsset WEB_ASSETS[] = {", *table, "};", ""]
text = "\n".join(lines)
old = open(out_path).read() if os.path.exists(out_path) else None
if text != old:  # leave the file alone when nothing changed, so it doesn't force a rebuild
    with open(out_path, "w") as f:
        f.write(text)
print(f"embed_web: {len(table)} files, {raw_total // 1024} KB -> {gz_total // 1024} KB gzipped")
